// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqSz-gQc1MtZojh7AoqULv5xtVe1jp_jY',
    appId: '1:604942026658:web:eae5c5f68b39173ea914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    authDomain: 'realstate-3e60d.firebaseapp.com',
    storageBucket: 'realstate-3e60d.appspot.com',
    measurementId: 'G-1JD56RVXY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjlwPMl_w8T4ogMubk24r5cBrtcueMyS8',
    appId: '1:604942026658:android:ba39b8f0bc54d8f1a914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    storageBucket: 'realstate-3e60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgQzk8FxKbNEsNxrT25MGuzUZWE65_byI',
    appId: '1:604942026658:ios:350fdfa0d8eabe18a914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    storageBucket: 'realstate-3e60d.appspot.com',
    iosBundleId: 'com.hifah.realestate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgQzk8FxKbNEsNxrT25MGuzUZWE65_byI',
    appId: '1:604942026658:ios:b451f5f746637c2fa914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    storageBucket: 'realstate-3e60d.appspot.com',
    iosBundleId: 'com.example.realstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqSz-gQc1MtZojh7AoqULv5xtVe1jp_jY',
    appId: '1:604942026658:web:b79f184b9a442abba914fb',
    messagingSenderId: '604942026658',
    projectId: 'realstate-3e60d',
    authDomain: 'realstate-3e60d.firebaseapp.com',
    storageBucket: 'realstate-3e60d.appspot.com',
    measurementId: 'G-0B0T1G8GF3',
  );
}
